id: A44C7747B
base_file: f82FC.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:13:54.768382
  last_modified_at: 2022-05-30 22:13:54.768391
